/* Koqnitiv Davranış Terapiyası Kursu — Ortaq JS mühərriki
   By s_akhundoff — https://instagram.com/s_akhundoff */

// Scroll-da bölmələrin görünməsi
const io = new IntersectionObserver((entries)=>{
  entries.forEach(e=>{ if(e.isIntersecting){ e.target.classList.add('show'); io.unobserve(e.target);} });
},{threshold:0.1});
document.addEventListener('DOMContentLoaded', ()=>{
  document.querySelectorAll('section').forEach(s=>io.observe(s));
});

// Parallax fon "blob"ları
window.addEventListener('mousemove', e=>{
  const mx = (e.clientX/window.innerWidth - 0.5);
  const my = (e.clientY/window.innerHeight - 0.5);
  document.querySelectorAll('.blob').forEach((b,i)=>{
    const speed = (i+1)*16;
    b.style.transform = `translate(${mx*speed}px, ${my*speed}px)`;
  });
});

// ---- Dil aşkarlama və UI mətnləri ----
function currentLang(){
  const l = (document.documentElement.lang || 'az').toLowerCase();
  if(l.startsWith('en')) return 'en';
  if(l.startsWith('ru')) return 'ru';
  if(l.startsWith('tr')) return 'tr';
  return 'az';
}
const UI = {
  az: { session:'Seans', therapist:'Terapevt', client:'Klient', mother:'Ana', father:'Ata',
    about:'📖 Seans haqqında', goal:'🎯 Məqsəd', specialists:'🩺 Kimlər tətbiq edə bilər',
    materials:'🧰 İstifadə olunan ləvazimatlar', flow:'📋 Seansın gedişi', homework:'📝 Ev tapşırığı',
    prev:'◂ Əvvəlki seans', next:'Növbəti seans ▸',
    programTag:'Proqram / Texnika', history:'📖 Tarixçə və kontekst', purpose:'🎯 Təyinatı',
    usage:'🛠️ İstifadə yönümü', outcomes:'📈 Nəticələri', notFound:'Məlumat tapılmadı.' },
  en: { session:'Session', therapist:'Therapist', client:'Client', mother:'Mother', father:'Father',
    about:'📖 About this session', goal:'🎯 Goal', specialists:'🩺 Who can apply this',
    materials:'🧰 Materials used', flow:'📋 Session flow', homework:'📝 Homework',
    prev:'◂ Previous session', next:'Next session ▸',
    programTag:'Program / Technique', history:'📖 Background and context', purpose:'🎯 Purpose',
    usage:'🛠️ How it is used', outcomes:'📈 Outcomes', notFound:'Information not found.' },
  ru: { session:'Сессия', therapist:'Терапевт', client:'Клиент', mother:'Мать', father:'Отец',
    about:'📖 О сессии', goal:'🎯 Цель', specialists:'🩺 Кто может применять',
    materials:'🧰 Используемые материалы', flow:'📋 Ход сессии', homework:'📝 Домашнее задание',
    prev:'◂ Предыдущая сессия', next:'Следующая сессия ▸',
    programTag:'Программа / Техника', history:'📖 История и контекст', purpose:'🎯 Назначение',
    usage:'🛠️ Как используется', outcomes:'📈 Результаты', notFound:'Информация не найдена.' },
  tr: { session:'Seans', therapist:'Terapist', client:'Danışan', mother:'Anne', father:'Baba',
    about:'📖 Seans hakkında', goal:'🎯 Amaç', specialists:'🩺 Kimler uygulayabilir',
    materials:'🧰 Kullanılan materyaller', flow:'📋 Seansın akışı', homework:'📝 Ev ödevi',
    prev:'◂ Önceki seans', next:'Sonraki seans ▸',
    programTag:'Program / Teknik', history:'📖 Geçmiş ve bağlam', purpose:'🎯 Amacı',
    usage:'🛠️ Kullanım şekli', outcomes:'📈 Sonuçları', notFound:'Bilgi bulunamadı.' }
};

// ---- Seans Modal Mühərriki ----
// Hər səhifə öz SESSIONS massivini və TOTAL_SESSIONS dəyərini təyin etməlidir
function renderSession(s){
  const t = UI[currentLang()];
  const total = (typeof TOTAL_SESSIONS !== 'undefined') ? TOTAL_SESSIONS : s.num;
  let html = `<span class="m-tag">${t.session} ${s.num} / ${total}</span><h3 class="m-title">${s.title}</h3>`;
  if(s.about){
    html += `<div class="m-block"><h5>${t.about}</h5><div class="m-goal">${s.about}</div></div>`;
  }
  html += `<div class="m-block"><h5>${t.goal}</h5><div class="m-goal">${s.goal}</div></div>`;
  if(s.specialists && s.specialists.length){
    html += `<div class="m-block"><h5>${t.specialists}</h5><div class="m-materials">${s.specialists.map(m=>`<span>${m}</span>`).join('')}</div></div>`;
  }
  if(s.materials && s.materials.length){
    html += `<div class="m-block"><h5>${t.materials}</h5><div class="m-materials">${s.materials.map(m=>`<span>${m}</span>`).join('')}</div></div>`;
  }
  html += `<div class="m-block"><h5>${t.flow}</h5>`;
  s.phases.forEach(ph=>{
    html += `<div class="m-phase"><div class="ph-name">${ph.name}</div>`;
    (ph.text||[]).forEach(x=>{ html += `<p>${x}</p>`; });
    if(ph.dialog && ph.dialog.length){
      html += `<div class="m-dialog">`;
      ph.dialog.forEach(d=>{
        const who = d[0]==='T' ? t.therapist : (d[0]==='K' ? t.client : (d[0]==='M' ? t.mother : (d[0]==='F' ? t.father : d[0])));
        const cls = d[0]==='T' ? 't' : 'k';
        html += `<div class="dl"><span class="dw ${cls}">${who}:</span><span class="dt">${d[1]}</span></div>`;
      });
      html += `</div>`;
    }
    html += `</div>`;
  });
  html += `</div>`;
  if(s.homework){
    html += `<div class="m-block"><h5>${t.homework}</h5><div class="m-homework">${s.homework}</div></div>`;
  }
  html += `<div class="m-nextprev">
    <div class="m-navbtn ${s.num<=1?'disabled':''}" onclick="openSession(${s.num-1})">${t.prev}</div>
    <div class="m-navbtn ${s.num>=total?'disabled':''}" onclick="openSession(${s.num+1})">${t.next}</div>
  </div>`;
  return html;
}

function openSession(n){
  if(typeof SESSIONS === 'undefined') return;
  const s = SESSIONS.find(x=>x.num===n);
  if(!s) return;
  document.getElementById('modalContent').innerHTML = renderSession(s);
  document.getElementById('modalOverlay').classList.add('active');
  document.body.classList.add('modal-open');
  const box = document.querySelector('.modal-box');
  if(box) box.scrollTop = 0;
}
function closeSession(){
  const ov = document.getElementById('modalOverlay');
  if(ov) ov.classList.remove('active');
  document.body.classList.remove('modal-open');
}
document.addEventListener('keydown', e=>{ if(e.key==='Escape') closeSession(); });

// ==================================================================
// PROGRAM/TEXNİKA LÜĞƏTİ MODALI — By s_akhundoff
// Mətn daxilində keçən terapiya proqramı/texnika adlarına klikləyəndə
// geniş məlumat (tarixçə, təyinat, istifadə, nəticələr) göstərir.
// Hər açar altında az/en/ru/tr tərcümələri saxlanılır.
// ==================================================================
const PROGRAMS_DB = {
"sistematik-desensitizasiya": {
  az:{title:"Sistematik Desensitizasiya", about:"Joseph Wolpe tərəfindən 1950-ci illərdə inkişaf etdirilmiş klassik davranış terapiyası texnikasıdır. Qarşılıqlı ləğvetmə (reciprocal inhibition) prinsipinə əsaslanır — relaksasiya hissi qorxu hissi ilə eyni anda mövcud ola bilmədiyi üçün, tədricən qorxu obyektinə yaxınlaşarkən bədən sakit saxlanılır.", purpose:"Fobiya və şiddətli qorxu reaksiyalarını, klienti birbaşa ən qorxulu vəziyyətə atmadan, tədricən azaltmaq.", usage:"Əvvəlcə qorxu hiyerarxiyası (asandan çətinə pillələr) qurulur, sonra relaksasiya bacarığı öyrədilir, daha sonra hər pillə relaksasiya vəziyyətində, ən aşağı pillədən başlayaraq tədricən keçilir.", outcomes:"Tədqiqatlar spesifik fobiyalarda yüksək effektivlik göstərir; irəliləyiş adətən pillə-pillə, bir neçə həftə-ay ərzində müşahidə olunur."},
  en:{title:"Systematic Desensitization", about:"A classic behavior therapy technique developed by Joseph Wolpe in the 1950s. It rests on the principle of reciprocal inhibition — since a state of relaxation cannot coexist with a state of fear, the body is kept calm while gradually approaching the feared object.", purpose:"To gradually reduce phobic and severe fear reactions, without ever placing the client directly into the most frightening situation.", usage:"A fear hierarchy is built first (steps from easiest to hardest), relaxation skills are taught, and then each step is worked through gradually while in a relaxed state, starting from the lowest step.", outcomes:"Research shows high effectiveness for specific phobias; progress is usually observed step by step, over several weeks to months."},
  ru:{title:"Систематическая десенсибилизация", about:"Классическая техника поведенческой терапии, разработанная Джозефом Вольпе в 1950-х годах. Основана на принципе взаимного торможения (reciprocal inhibition) — поскольку состояние расслабления не может существовать одновременно со страхом, тело сохраняют спокойным при постепенном приближении к пугающему объекту.", purpose:"Постепенно снижать фобические реакции и сильный страх, не помещая клиента сразу в самую пугающую ситуацию.", usage:"Сначала строится иерархия страха (ступени от лёгкого к трудному), затем обучают навыку релаксации, после чего каждая ступень постепенно проходится в расслабленном состоянии, начиная с самой нижней.", outcomes:"Исследования показывают высокую эффективность при специфических фобиях; прогресс обычно наблюдается постепенно, в течение нескольких недель-месяцев."},
  tr:{title:"Sistematik Duyarsızlaştırma", about:"Joseph Wolpe tarafından 1950'lerde geliştirilen klasik bir davranış terapisi tekniğidir. Karşılıklı ketleme (reciprocal inhibition) ilkesine dayanır — gevşeme hissi korku hissiyle aynı anda var olamayacağı için, korku nesnesine kademeli olarak yaklaşırken beden sakin tutulur.", purpose:"Fobik ve şiddetli korku tepkilerini, danışanı doğrudan en korkutucu duruma sokmadan, kademeli olarak azaltmak.", usage:"Önce bir korku hiyerarşisi (kolaydan zora basamaklar) kurulur, sonra gevşeme becerisi öğretilir, ardından her basamak gevşemiş durumdayken, en alt basamaktan başlanarak kademeli olarak geçilir.", outcomes:"Araştırmalar spesifik fobilerde yüksek etkinlik gösteriyor; ilerleme genellikle adım adım, birkaç hafta-ay içinde gözlenir."}
},
"tedrici-meruzeetme": {
  az:{title:"Tədrici Məruzəetmə (Graded Exposure)", about:"Məruzəetmə terapiyasının əsas formalarından biri olub, davranış terapiyasının nüvəsini təşkil edir.", purpose:"Qaçınma davranışını aradan qaldırmaq və qorxunun zamanla öz-özünə azaldığını (habituasiya) təcrübədən keçirtmək.", usage:"Qorxulu vəziyyətlər asandan çətinə sıralanır, hər addımda narahatlıq termometrlə izlənilir, addım narahatlıq azalana qədər davam etdirilir, sonra növbəti pilləyə keçilir.", outcomes:"Fobiya, sosial narahatlıq və panik pozuntularda ən çox dəstəklənən müalicə üsullarından biridir."},
  en:{title:"Graded Exposure", about:"One of the core forms of exposure therapy, and it forms the backbone of behavior therapy.", purpose:"To eliminate avoidance behavior and let the client experience firsthand that fear reduces on its own over time (habituation).", usage:"Feared situations are ranked from easiest to hardest; anxiety is tracked with a thermometer at each step, the step is continued until anxiety drops, then the client moves to the next one.", outcomes:"One of the most well-supported treatments for phobias, social anxiety, and panic disorder."},
  ru:{title:"Постепенная экспозиция (Graded Exposure)", about:"Одна из основных форм экспозиционной терапии, составляющая ядро поведенческой терапии.", purpose:"Устранить избегающее поведение и дать клиенту на собственном опыте убедиться, что страх со временем снижается сам по себе (привыкание).", usage:"Пугающие ситуации ранжируются от лёгких к трудным, на каждом шаге тревога отслеживается термометром, шаг продолжается до снижения тревоги, затем переходят к следующему.", outcomes:"Один из наиболее подтверждённых методов лечения фобий, социальной тревожности и панического расстройства."},
  tr:{title:"Kademeli Maruz Bırakma (Graded Exposure)", about:"Maruz bırakma terapisinin temel biçimlerinden biridir ve davranış terapisinin çekirdeğini oluşturur.", purpose:"Kaçınma davranışını ortadan kaldırmak ve korkunun zamanla kendiliğinden azaldığını (alışma) deneyimletmek.", usage:"Korkulan durumlar kolaydan zora sıralanır, her adımda kaygı termometreyle izlenir, kaygı azalana kadar o adımda kalınır, sonra bir sonraki basamağa geçilir.", outcomes:"Fobi, sosyal kaygı ve panik bozukluğunda en çok desteklenen tedavi yöntemlerinden biridir."}
},
"erp": {
  az:{title:"ERP — Məruzəetmə və Cavabın Qarşısının Alınması", about:"Obsessiv-Kompulsiv Pozuntunun (OKB) qızıl standart müalicəsi sayılır, 1960-70-ci illərdə Viktor Meyer tərəfindən əsası qoyulmuşdur.", purpose:"Obsessiyanın yaratdığı narahatlığı kompulsiya (ritual) etmədən yaşamağı öyrətmək və beynin 'təhlükə yoxdur' siqnalını təbii yolla almasını təmin etmək.", usage:"Klient narahatlıq yaradan vəziyyətə (məs. çirkli səthə toxunma) məruz qalır, lakin adət etdiyi kompulsiyanı (əl yuma) etmək qadağandır; narahatlıq özbaşına azalana qədər gözlənilir.", outcomes:"Tədqiqatlarda OKB simptomlarının 60-80% azalması müşahidə olunur, effekt uzunmüddətli olur."},
  en:{title:"ERP — Exposure and Response Prevention", about:"Considered the gold-standard treatment for Obsessive-Compulsive Disorder (OCD); its foundation was laid by Victor Meyer in the 1960s-70s.", purpose:"To teach the client to sit with the anxiety an obsession creates without performing the compulsion (ritual), letting the brain naturally receive the signal that 'there is no danger.'", usage:"The client is exposed to an anxiety-provoking situation (e.g. touching a dirty surface), but is prevented from performing the usual compulsion (handwashing); they wait until the anxiety decreases on its own.", outcomes:"Studies show a 60-80% reduction in OCD symptoms, with long-lasting effects."},
  ru:{title:"ЭПР — Экспозиция и предотвращение реакции", about:"Считается золотым стандартом лечения обсессивно-компульсивного расстройства (ОКР); основы заложены Виктором Мейером в 1960-70-х годах.", purpose:"Научить клиента переживать тревогу, вызванную навязчивой мыслью, не выполняя компульсию (ритуал), позволяя мозгу естественным путём получить сигнал 'опасности нет'.", usage:"Клиент подвергается воздействию тревожной ситуации (например, прикосновению к грязной поверхности), но ему запрещено выполнять привычную компульсию (мытьё рук); ожидание продолжается, пока тревога не снизится сама.", outcomes:"В исследованиях наблюдается снижение симптомов ОКР на 60-80%, эффект сохраняется долгосрочно."},
  tr:{title:"ERP — Maruz Bırakma ve Tepki Önleme", about:"Obsesif-Kompulsif Bozukluğun (OKB) altın standart tedavisi sayılır; temelleri 1960-70'lerde Victor Meyer tarafından atılmıştır.", purpose:"Danışana obsesyonun yarattığı kaygıyı kompulsiyon (ritüel) yapmadan yaşamayı öğretmek ve beynin 'tehlike yok' sinyalini doğal yoldan almasını sağlamak.", usage:"Danışan kaygı yaratan bir duruma (örn. kirli bir yüzeye dokunma) maruz bırakılır, ama alıştığı kompulsiyonu (el yıkama) yapması engellenir; kaygı kendiliğinden azalana kadar beklenir.", outcomes:"Araştırmalarda OKB semptomlarında %60-80 azalma gözlenir, etki uzun sürelidir."}
},
"reqabetli-cavab": {
  az:{title:"Rəqabətli Cavab Öyrədilməsi (Competing Response Training)", about:"Habit Reversal Training (Vərdişin Tərsinə Çevrilməsi) müalicəsinin əsas komponentidir, Azrin və Nunn tərəfindən 1970-ci illərdə hazırlanmışdır.", purpose:"Tikə fiziki olaraq zidd, lakin sosial baxımdan qəbul edilən alternativ hərəkət öyrətməklə tikin tezliyini azaltmaq.", usage:"Əvvəlcə tikdən öncəki bədən siqnalı (premonitory urge) tanınır, sonra bu siqnal gələndə tikə zidd əzələ hərəkəti (məs. boyun tiki üçün boyunu yavaş gərginləşdirmək) 1 dəqiqəyə yaxın tətbiq edilir.", outcomes:"Tourett sindromu və xroniki tik pozuntularında elmi cəhətdən ən çox dəstəklənən davranış müdaxiləsidir."},
  en:{title:"Competing Response Training", about:"The core component of Habit Reversal Training, developed by Azrin and Nunn in the 1970s.", purpose:"To reduce the frequency of a tic by teaching an alternative movement that is physically incompatible with it but socially acceptable.", usage:"The premonitory urge preceding the tic is first recognized; when that signal appears, a muscle movement opposite to the tic (e.g. slowly tensing the neck for a neck tic) is applied for close to a minute.", outcomes:"The most scientifically supported behavioral intervention for Tourette syndrome and chronic tic disorders."},
  ru:{title:"Обучение конкурирующей реакции (Competing Response Training)", about:"Основной компонент терапии обращения привычки (Habit Reversal Training), разработанной Азрином и Нанном в 1970-х годах.", purpose:"Снизить частоту тика, обучив альтернативному движению, физически несовместимому с тиком, но социально приемлемому.", usage:"Сначала распознаётся предшествующий тику телесный сигнал (premonitory urge), затем при его появлении применяется противоположное тику движение мышц (например, медленное напряжение шеи при тике шеи) в течение около минуты.", outcomes:"Наиболее научно обоснованное поведенческое вмешательство при синдроме Туретта и хронических тикозных расстройствах."},
  tr:{title:"Rekabetçi Tepki Eğitimi (Competing Response Training)", about:"Alışkanlık Tersine Çevirme Eğitiminin (Habit Reversal Training) temel bileşenidir, Azrin ve Nunn tarafından 1970'lerde geliştirilmiştir.", purpose:"Tike fiziksel olarak zıt ama sosyal açıdan kabul edilebilir alternatif bir hareket öğreterek tikin sıklığını azaltmak.", usage:"Önce tikten önceki beden sinyali (premonitory urge) tanınır, bu sinyal geldiğinde tike zıt bir kas hareketi (örn. boyun tiki için boynu yavaşça gerdirmek) yaklaşık 1 dakika uygulanır.", outcomes:"Tourette sendromu ve kronik tik bozukluklarında bilimsel olarak en çok desteklenen davranışsal müdahaledir."}
},
"nezaret-dairesi": {
  az:{title:"Nəzarət Dairəsi Texnikası", about:"Stress idarəetməsində geniş istifadə olunan koqnitiv-davranış alətidir, stoisizm fəlsəfəsindəki 'nəzarət dixotomiyası' ideyasına əsaslanır.", purpose:"Enerjini dəyişdirə bilmədiyimiz şeylərdən, dəyişdirə biləcəyimiz konkret addımlara yönləndirmək.", usage:"İki dairə çəkilir: xarici dairəyə narahatlıq yaradan bütün amillər, daxili kiçik dairəyə isə yalnız şəxsin real nəzarət edə biləcəyi addımlar yazılır.", outcomes:"Çarəsizlik hissini azaldır, problemə fokuslanmış baş etmə strategiyalarını gücləndirir."},
  en:{title:"Circle of Control Technique", about:"A widely used cognitive-behavioral tool for stress management, based on the Stoic philosophical idea of the 'dichotomy of control.'", purpose:"To redirect energy away from things we cannot change and toward concrete steps we actually can.", usage:"Two circles are drawn: the outer circle holds everything causing worry, the small inner circle holds only the steps the person can genuinely control.", outcomes:"Reduces the sense of helplessness and strengthens problem-focused coping strategies."},
  ru:{title:"Техника «Круг контроля»", about:"Широко используемый когнитивно-поведенческий инструмент управления стрессом, основанный на стоической идее «дихотомии контроля».", purpose:"Перенаправить энергию с того, что мы не можем изменить, на конкретные шаги, которые мы действительно можем предпринять.", usage:"Рисуются два круга: во внешний круг вписывают всё, что вызывает тревогу, во внутренний маленький круг — только те шаги, которые человек реально может контролировать.", outcomes:"Снижает чувство беспомощности, укрепляет стратегии совладания, сфокусированные на решении проблемы."},
  tr:{title:"Kontrol Dairesi Tekniği", about:"Stres yönetiminde yaygın kullanılan bilişsel-davranışçı bir araçtır, Stoacı felsefedeki 'kontrol ikilemi' fikrine dayanır.", purpose:"Enerjiyi değiştiremediğimiz şeylerden, gerçekten değiştirebileceğimiz somut adımlara yönlendirmek.", usage:"İki daire çizilir: dış daireye kaygı yaratan her şey, iç küçük daireye ise kişinin gerçekten kontrol edebileceği adımlar yazılır.", outcomes:"Çaresizlik hissini azaltır, probleme odaklı baş etme stratejilerini güçlendirir."}
},
"narahatliq-vaxti": {
  az:{title:"Narahatlıq Vaxtı Texnikası (Worry Time)", about:"Ümumiləşmiş Narahatlıq Pozuntusunun (GAD) müalicəsində Borkovec tərəfindən təklif olunmuş stimul-nəzarəti texnikasıdır.", purpose:"Narahat fikirlərin gün boyu yayılmasının qarşısını alaraq, onları məhdud, təyin olunmuş vaxta 'toplamaq'.", usage:"Gün ərzində narahat fikir yarandıqda yazılıb təxirə salınır, gündə əvvəlcədən razılaşdırılmış 10-15 dəqiqəlik sabit vaxtda bu fikirlərə düşünülür.", outcomes:"Narahatlığın gündəlik funksionallığa müdaxiləsini azaldır, nəzarət hissini artırır."},
  en:{title:"Worry Time Technique", about:"A stimulus-control technique proposed by Borkovec for treating Generalized Anxiety Disorder (GAD).", purpose:"To stop worried thoughts from spreading across the whole day by 'collecting' them into a limited, designated time slot.", usage:"When a worried thought comes up during the day, it's written down and postponed; those thoughts are then reflected on during a pre-agreed, fixed 10-15 minute window each day.", outcomes:"Reduces worry's interference with daily functioning and increases the sense of control."},
  ru:{title:"Техника «Время для тревоги» (Worry Time)", about:"Техника контроля стимула, предложенная Борковеком для лечения генерализованного тревожного расстройства (ГТР).", purpose:"Остановить распространение тревожных мыслей на весь день, «собирая» их в ограниченный, заранее назначенный промежуток времени.", usage:"Когда в течение дня появляется тревожная мысль, она записывается и откладывается; эти мысли обдумываются в заранее согласованное, фиксированное окно в 10-15 минут каждый день.", outcomes:"Снижает вмешательство тревоги в повседневное функционирование, усиливает чувство контроля."},
  tr:{title:"Kaygı Zamanı Tekniği (Worry Time)", about:"Yaygın Anksiyete Bozukluğunun (GAD) tedavisinde Borkovec tarafından önerilen bir uyaran kontrolü tekniğidir.", purpose:"Kaygılı düşüncelerin gün boyu yayılmasını önleyerek onları sınırlı, belirlenmiş bir zamana 'toplamak'.", usage:"Gün içinde kaygılı bir düşünce geldiğinde yazılır ve ertelenir; bu düşünceler günde önceden kararlaştırılmış, sabit 10-15 dakikalık bir pencerede ele alınır.", outcomes:"Kaygının günlük işlevselliğe müdahalesini azaltır, kontrol hissini artırır."}
},
"qutu-nefesi": {
  az:{title:"Qutu Nəfəsi (Box Breathing)", about:"Diafraqmatik nəfəs texnikalarından biridir, hərbi və klinik kontekstlərdə geniş istifadə olunur (4-4-4-4 ritmi).", purpose:"Parasimpatik sinir sistemini aktivləşdirərək bədəni sürətlə sakitləşdirmək.", usage:"4 saniyə burundan nəfəs alınır, 4 saniyə saxlanılır, 4 saniyə ağızdan verilir, 4 saniyə yenə saxlanılır; dövr bir neçə dəfə təkrarlanır.", outcomes:"Ürək döyüntüsünü və subyektiv narahatlıq səviyyəsini bir neçə dəqiqə ərzində azalda bilir."},
  en:{title:"Box Breathing", about:"One of the diaphragmatic breathing techniques, widely used in military and clinical contexts (a 4-4-4-4 rhythm).", purpose:"To calm the body quickly by activating the parasympathetic nervous system.", usage:"Breathe in through the nose for 4 seconds, hold for 4 seconds, breathe out through the mouth for 4 seconds, hold again for 4 seconds; the cycle is repeated several times.", outcomes:"Can lower heart rate and subjective anxiety level within just a few minutes."},
  ru:{title:"Квадратное дыхание (Box Breathing)", about:"Одна из диафрагмальных дыхательных техник, широко используемая в военном и клиническом контексте (ритм 4-4-4-4).", purpose:"Быстро успокоить тело, активировав парасимпатическую нервную систему.", usage:"Вдох через нос на 4 секунды, задержка на 4 секунды, выдох через рот на 4 секунды, снова задержка на 4 секунды; цикл повторяется несколько раз.", outcomes:"Способно снизить частоту сердечных сокращений и субъективный уровень тревоги всего за несколько минут."},
  tr:{title:"Kutu Nefesi (Box Breathing)", about:"Diyaframatik nefes tekniklerinden biridir, askeri ve klinik bağlamlarda yaygın kullanılır (4-4-4-4 ritmi).", purpose:"Parasempatik sinir sistemini aktive ederek bedeni hızla sakinleştirmek.", usage:"Burundan 4 saniye nefes alınır, 4 saniye tutulur, ağızdan 4 saniye verilir, 4 saniye yine tutulur; döngü birkaç kez tekrarlanır.", outcomes:"Kalp atış hızını ve öznel kaygı düzeyini birkaç dakika içinde azaltabilir."}
},
"koqnitiv-restrukturizasiya": {
  az:{title:"Koqnitiv Restrukturizasiya", about:"Aaron Beck-in Koqnitiv Terapiya modelinin əsas texnikasıdır (1960-cı illər), faydasız düşüncə nümunələrinin sorğulanmasına yönəlib.", purpose:"Təhrif olunmuş, katastrofikləşdirici düşüncələri sübutla müqayisə edərək daha balanslaşdırılmış alternativlərlə əvəz etmək.", usage:"Avtomatik fikir qeydə alınır, dəstəkləyici və əks sübutlar axtarılır, daha realist balanslaşdırılmış fikir formalaşdırılır.", outcomes:"Depressiya, narahatlıq və s. pozuntularda simptomların azalmasına dair güclü elmi dəstək var."},
  en:{title:"Cognitive Restructuring", about:"The core technique of Aaron Beck's Cognitive Therapy model (1960s), focused on questioning unhelpful thought patterns.", purpose:"To replace distorted, catastrophizing thoughts with more balanced alternatives by weighing them against the evidence.", usage:"The automatic thought is recorded, supporting and contradicting evidence is gathered, and a more realistic, balanced thought is formed.", outcomes:"Strong scientific support for reducing symptoms in depression, anxiety, and related disorders."},
  ru:{title:"Когнитивная реструктуризация", about:"Основная техника модели когнитивной терапии Аарона Бека (1960-е годы), направленная на проверку бесполезных паттернов мышления.", purpose:"Заменить искажённые, катастрофизирующие мысли более сбалансированными альтернативами, сопоставляя их с доказательствами.", usage:"Автоматическая мысль фиксируется, ищутся подтверждающие и опровергающие доказательства, формируется более реалистичная, сбалансированная мысль.", outcomes:"Сильная научная поддержка снижения симптомов при депрессии, тревоге и связанных расстройствах."},
  tr:{title:"Bilişsel Yeniden Yapılandırma", about:"Aaron Beck'in Bilişsel Terapi modelinin temel tekniğidir (1960'lar), işe yaramayan düşünce kalıplarının sorgulanmasına odaklanır.", purpose:"Çarpıtılmış, felaketleştirici düşünceleri kanıtla karşılaştırarak daha dengeli alternatiflerle değiştirmek.", usage:"Otomatik düşünce kaydedilir, destekleyici ve karşıt kanıtlar aranır, daha gerçekçi, dengeli bir düşünce oluşturulur.", outcomes:"Depresyon, kaygı ve benzeri bozukluklarda semptomların azalmasına dair güçlü bilimsel destek vardır."}
},
"davranis-aktivlesdirmesi": {
  az:{title:"Davranış Aktivləşdirilməsi (Behavioral Activation)", about:"Depressiyanın müalicəsində müstəqil, effektiv bir yanaşma kimi 1990-2000-ci illərdə inkişaf etmişdir (Jacobson və b.).", purpose:"Passivlik-enerjisizlik dövranını qırmaq üçün kiçik, zövq və məna verən fəaliyyətləri tədricən bərpa etmək.", usage:"Əvvəllər zövq verən fəaliyyətlər müəyyənləşdirilir, kiçik, real addımlarla planlaşdırılır və fəaliyyət-əhval əlaqəsi izlənilir.", outcomes:"Bir çox tədqiqatda koqnitiv terapiya qədər effektiv olduğu göstərilmişdir."},
  en:{title:"Behavioral Activation", about:"Developed as an independent, effective approach to treating depression in the 1990s-2000s (Jacobson et al.).", purpose:"To break the passivity-low energy cycle by gradually restoring small, enjoyable, and meaningful activities.", usage:"Previously enjoyable activities are identified, planned in small, realistic steps, and the link between activity and mood is tracked.", outcomes:"Shown in many studies to be as effective as cognitive therapy."},
  ru:{title:"Поведенческая активация (Behavioral Activation)", about:"Разработана как самостоятельный, эффективный подход к лечению депрессии в 1990-2000-х годах (Джейкобсон и др.).", purpose:"Разорвать цикл пассивности и бессилия, постепенно восстанавливая небольшие, приятные и значимые виды деятельности.", usage:"Определяются ранее приятные занятия, планируются небольшими, реальными шагами, отслеживается связь между активностью и настроением.", outcomes:"Во многих исследованиях показана эффективность, сопоставимая с когнитивной терапией."},
  tr:{title:"Davranışsal Aktivasyon (Behavioral Activation)", about:"Depresyon tedavisinde bağımsız, etkili bir yaklaşım olarak 1990-2000'lerde geliştirilmiştir (Jacobson ve ark.).", purpose:"Pasiflik-enerjisizlik döngüsünü kırmak için küçük, keyif ve anlam veren etkinlikleri kademeli olarak yeniden kazandırmak.", usage:"Daha önce keyif veren etkinlikler belirlenir, küçük, gerçekçi adımlarla planlanır ve etkinlik-ruh hali bağlantısı izlenir.", outcomes:"Birçok araştırmada bilişsel terapi kadar etkili olduğu gösterilmiştir."}
},
"food-chaining": {
  az:{title:"Food Chaining (Tədrici Qida Tanışlığı)", about:"Seçici yemə (Avoidant/Restrictive Food Intake Disorder-ə yaxın hallar) üçün loqoped/erqoterapevt sahəsində istifadə olunan müdaxilədir.", purpose:"Yeni qidaları, artıq qəbul edilən qidalara bənzərliyi (rəng, toxuma, dad) əsasında tədricən repertuara daxil etmək.", usage:"Uşağın 'təhlükəsiz' saydığı qidaya toxuma/dad baxımından ən yaxın yeni qida seçilir və kiçik addımlarla (baxmaq→iyləmək→toxunmaq→dadmaq) təqdim olunur.", outcomes:"Yemək repertuarının, təzyiq olmadan, tədricən genişlənməsinə imkan verir."},
  en:{title:"Food Chaining", about:"An intervention used in speech-language and occupational therapy for selective eating (conditions close to Avoidant/Restrictive Food Intake Disorder).", purpose:"To gradually expand the food repertoire by introducing new foods based on their similarity (color, texture, taste) to already-accepted foods.", usage:"A new food closest in texture/taste to a food the child already considers 'safe' is chosen and introduced in small steps (look → smell → touch → taste).", outcomes:"Allows the food repertoire to expand gradually, without pressure."},
  ru:{title:"Пищевая цепочка (Food Chaining)", about:"Вмешательство, применяемое в логопедии/эрготерапии при избирательном питании (состояния, близкие к избегающему/ограничительному расстройству приёма пищи).", purpose:"Постепенно расширять пищевой репертуар, вводя новые продукты на основе их сходства (цвет, текстура, вкус) с уже принимаемыми продуктами.", usage:"Выбирается новый продукт, наиболее близкий по текстуре/вкусу к продукту, который ребёнок уже считает «безопасным», и вводится небольшими шагами (посмотреть → понюхать → потрогать → попробовать).", outcomes:"Позволяет постепенно, без давления, расширять пищевой репертуар."},
  tr:{title:"Food Chaining (Kademeli Besin Tanıtımı)", about:"Seçici yeme (Kaçıngan/Kısıtlayıcı Besin Alımı Bozukluğuna yakın durumlar) için dil ve konuşma terapisi/ergoterapi alanında kullanılan bir müdahaledir.", purpose:"Zaten kabul edilen besinlere benzerliği (renk, doku, tat) temelinde yeni besinleri kademeli olarak repertuara katmak.", usage:"Çocuğun 'güvenli' saydığı besine doku/tat açısından en yakın yeni besin seçilir ve küçük adımlarla (bakmak→koklamak→dokunmak→tatmak) sunulur.", outcomes:"Besin repertuarının baskı olmadan kademeli olarak genişlemesine imkân tanır."}
},
"sensor-desensitizasiya": {
  az:{title:"Sensor Desensitizasiya", about:"Sensor İnteqrasiya nəzəriyyəsinə (A. Jean Ayres) əsaslanan erqoterapiya müdaxiləsidir.", purpose:"Həddindən artıq həssas sensor sistemi tədricən, təzyiqsiz məruzəetmə ilə 'öyrətmək'.", usage:"Stimul ilə tanışlıq ən aşağı intensivlikdən (baxmaq) başlayaraq, klientin öz sürəti ilə daha yüksək intensivliyə (toxunma, dadma) doğru irəlilədilir.", outcomes:"Sensor həssaslığın azalması və gündəlik fəaliyyətlərə (yemək, geyim və s.) daha rahat qatılma."},
  en:{title:"Sensory Desensitization", about:"An occupational therapy intervention based on Sensory Integration theory (A. Jean Ayres).", purpose:"To gradually 'retrain' an oversensitive sensory system through pressure-free exposure.", usage:"Familiarization with the stimulus starts at the lowest intensity (looking), and moves toward higher intensity (touching, tasting) at the client's own pace.", outcomes:"Reduced sensory sensitivity and more comfortable participation in daily activities (eating, dressing, etc.)."},
  ru:{title:"Сенсорная десенсибилизация", about:"Вмешательство эрготерапии, основанное на теории сенсорной интеграции (А. Джин Айрес).", purpose:"Постепенно «переобучить» чрезмерно чувствительную сенсорную систему через экспозицию без давления.", usage:"Знакомство со стимулом начинается с самой низкой интенсивности (смотреть) и продвигается к более высокой интенсивности (трогать, пробовать) в темпе клиента.", outcomes:"Снижение сенсорной чувствительности и более комфортное участие в повседневной деятельности (еда, одевание и т.д.)."},
  tr:{title:"Duyusal Duyarsızlaştırma", about:"Duyu Bütünleme kuramına (A. Jean Ayres) dayanan bir ergoterapi müdahalesidir.", purpose:"Aşırı hassas duyusal sistemi baskısız maruz bırakma yoluyla kademeli olarak 'yeniden eğitmek'.", usage:"Uyaranla tanışma en düşük yoğunluktan (bakmak) başlayarak, danışanın kendi hızında daha yüksek yoğunluğa (dokunmak, tatmak) doğru ilerletilir.", outcomes:"Duyusal hassasiyetin azalması ve günlük etkinliklere (yeme, giyinme vb.) daha rahat katılım."}
},
"vizuallasdirma": {
  az:{title:"Vizuallaşdırma Texnikası (Guided Imagery)", about:"İdman psixologiyası və koqnitiv-davranış terapiyasında geniş istifadə olunan zehni məşq üsuludur.", purpose:"Özünəinamı artırmaq və gələcək stresli hadisəyə (imtahan, çıxış) zehni hazırlıq yaratmaq.", usage:"Klient gözlərini yumaraq, bütün hisslərini işə salaraq, uğurlu nəticəni addım-addım təsəvvüründə canlandırır.", outcomes:"Performans narahatlığını azaldır, özünəinam və hazırlıq hissini gücləndirir."},
  en:{title:"Visualization Technique (Guided Imagery)", about:"A mental rehearsal method widely used in sports psychology and cognitive-behavioral therapy.", purpose:"To build self-confidence and create mental preparation for a future stressful event (an exam, a performance).", usage:"The client closes their eyes and, engaging all their senses, mentally rehearses a successful outcome step by step.", outcomes:"Reduces performance anxiety, strengthens self-confidence and a sense of preparedness."},
  ru:{title:"Техника визуализации (Guided Imagery)", about:"Метод мысленной репетиции, широко используемый в спортивной психологии и когнитивно-поведенческой терапии.", purpose:"Повысить уверенность в себе и создать мысленную подготовку к будущему стрессовому событию (экзамену, выступлению).", usage:"Клиент закрывает глаза и, задействуя все чувства, мысленно шаг за шагом проигрывает успешный исход.", outcomes:"Снижает тревогу по поводу результата, укрепляет уверенность в себе и чувство подготовленности."},
  tr:{title:"Görselleştirme Tekniği (Guided Imagery)", about:"Spor psikolojisi ve bilişsel davranışçı terapide yaygın kullanılan bir zihinsel prova yöntemidir.", purpose:"Özgüveni artırmak ve gelecekteki stresli bir olaya (sınav, performans) zihinsel hazırlık yaratmak.", usage:"Danışan gözlerini kapatarak, tüm duyularını devreye sokarak, başarılı sonucu adım adım zihninde canlandırır.", outcomes:"Performans kaygısını azaltır, özgüveni ve hazırlık hissini güçlendirir."}
},
"problem-hell": {
  az:{title:"Problem-Həll Bacarıqları Təlimi", about:"D'Zurilla və Goldfried tərəfindən 1970-ci illərdə formalaşdırılmış struktur yanaşmadır.", purpose:"Real, həll edilə bilən çətinliklərə qarşı çarəsizlik hissini azaldıb, konkret fəaliyyət planı qurma bacarığı aşılamaq.", usage:"Problem dəqiq təyin olunur, mümkün həll variantları sadalanır, hər birinin nəticəsi qiymətləndirilir, ən uyğun addım seçilib tətbiq olunur.", outcomes:"Depressiya və narahatlıqda çarəsizlik hissini azaldır, fəallığı artırır."},
  en:{title:"Problem-Solving Skills Training", about:"A structured approach formulated by D'Zurilla and Goldfried in the 1970s.", purpose:"To reduce feelings of helplessness toward real, solvable difficulties and instill the skill of building a concrete action plan.", usage:"The problem is defined precisely, possible solutions are listed, each is evaluated for its likely outcome, and the most suitable step is chosen and applied.", outcomes:"Reduces feelings of helplessness in depression and anxiety, and increases active coping."},
  ru:{title:"Тренинг навыков решения проблем", about:"Структурированный подход, разработанный Д'Зуриллой и Голдфридом в 1970-х годах.", purpose:"Снизить чувство беспомощности перед реальными, разрешимыми трудностями и привить навык построения конкретного плана действий.", usage:"Проблема точно определяется, перечисляются возможные решения, оценивается вероятный результат каждого, выбирается и применяется наиболее подходящий шаг.", outcomes:"Снижает чувство беспомощности при депрессии и тревоге, повышает активность в совладании."},
  tr:{title:"Problem Çözme Becerileri Eğitimi", about:"D'Zurilla ve Goldfried tarafından 1970'lerde formüle edilmiş yapılandırılmış bir yaklaşımdır.", purpose:"Gerçek, çözülebilir zorluklar karşısındaki çaresizlik hissini azaltıp somut bir eylem planı kurma becerisi kazandırmak.", usage:"Problem net olarak tanımlanır, olası çözümler sıralanır, her birinin sonucu değerlendirilir, en uygun adım seçilip uygulanır.", outcomes:"Depresyon ve kaygıda çaresizlik hissini azaltır, etkinliği artırır."}
},
"dayan-dusun-fealiyyet": {
  az:{title:"Dayan-Düşün-Fəaliyyət Göstər", about:"İmpulsiv davranışın idarə edilməsi üçün istifadə olunan sadələşdirilmiş özünütənzimləmə strategiyasıdır (DEHB müdaxilələrində geniş yayılıb).", purpose:"Ani reaksiya ilə fəaliyyət arasına şüurlu bir fasilə yaratmaq.", usage:"Reaksiya vermədən əvvəl qısaca 'dayan', mümkün nəticələr haqqında 'düşün', sonra ən uyğun addımı at.", outcomes:"İmpulsiv sosial və akademik səhvlərin azalmasına kömək edir."},
  en:{title:"Stop-Think-Act", about:"A simplified self-regulation strategy used to manage impulsive behavior (widely used in ADHD interventions).", purpose:"To create a conscious pause between an immediate reaction and an action.", usage:"Before reacting, briefly 'stop,' 'think' about the possible outcomes, then take the most suitable step.", outcomes:"Helps reduce impulsive social and academic mistakes."},
  ru:{title:"Остановись-Подумай-Действуй", about:"Упрощённая стратегия саморегуляции для управления импульсивным поведением (широко используется при СДВГ).", purpose:"Создать осознанную паузу между мгновенной реакцией и действием.", usage:"Перед тем как реагировать, кратко «остановись», «подумай» о возможных последствиях, затем сделай наиболее подходящий шаг.", outcomes:"Помогает снизить импульсивные социальные и учебные ошибки."},
  tr:{title:"Dur-Düşün-Davran", about:"Dürtüsel davranışı yönetmek için kullanılan basitleştirilmiş bir öz-düzenleme stratejisidir (DEHB müdahalelerinde yaygındır).", purpose:"Anlık tepki ile eylem arasında bilinçli bir duraklama yaratmak.", usage:"Tepki vermeden önce kısaca 'dur', olası sonuçlar hakkında 'düşün', sonra en uygun adımı at.", outcomes:"Dürtüsel sosyal ve akademik hataların azalmasına yardımcı olur."}
},
"cps": {
  az:{title:"Kollaborativ Problem Həlli (CPS)", about:"Dr. Ross Greene tərəfindən inkişaf etdirilmiş, 'uşaqlar bacardıqları qədər yaxşı davranırlar' fəlsəfəsinə əsaslanan yanaşmadır.", purpose:"Problemli davranışı 'pislik' deyil, çatışmayan bacarıq/ifadə olunmamış ehtiyacın nəticəsi kimi ələ alıb, birgə həll tapmaq.", usage:"Böyük, uşağın perspektivini empatiya ilə dinləyir, öz narahatlığını bildirir, sonra ikisi birlikdə qarşılıqlı qəbul edilən həll axtarır.", outcomes:"Partlayış epizodlarının tezliyini azaldır, valideyn-uşaq münasibətini yaxşılaşdırır."},
  en:{title:"Collaborative Problem Solving (CPS)", about:"An approach developed by Dr. Ross Greene, based on the philosophy that 'kids do well if they can.'", purpose:"To treat problem behavior not as 'badness' but as the result of a lagging skill or an unexpressed need, and find a solution together.", usage:"The adult listens to the child's perspective with empathy, shares their own concern, and then the two together search for a mutually acceptable solution.", outcomes:"Reduces the frequency of explosive episodes and improves the parent-child relationship."},
  ru:{title:"Совместное решение проблем (CPS)", about:"Подход, разработанный доктором Россом Грином, основанный на философии «дети ведут себя хорошо, если могут».", purpose:"Рассматривать проблемное поведение не как «плохость», а как результат недостающего навыка или невыраженной потребности, и находить решение вместе.", usage:"Взрослый с эмпатией выслушивает точку зрения ребёнка, делится собственной обеспокоенностью, затем вместе они ищут взаимоприемлемое решение.", outcomes:"Снижает частоту эпизодов срывов, улучшает отношения между родителем и ребёнком."},
  tr:{title:"İşbirlikçi Problem Çözme (CPS)", about:"Dr. Ross Greene tarafından geliştirilen, 'çocuklar yapabiliyorlarsa iyi davranırlar' felsefesine dayanan bir yaklaşımdır.", purpose:"Sorunlu davranışı 'kötülük' değil, eksik bir beceri ya da ifade edilmemiş bir ihtiyacın sonucu olarak ele alıp birlikte çözüm bulmak.", usage:"Yetişkin, çocuğun bakış açısını empatiyle dinler, kendi endişesini paylaşır, sonra ikisi birlikte karşılıklı kabul edilebilir bir çözüm arar.", outcomes:"Patlama epizodlarının sıklığını azaltır, ebeveyn-çocuk ilişkisini iyileştirir."}
},
"pacing": {
  az:{title:"Pacing (Enerji İdarəetməsi)", about:"Xroniki xəstəlik və yorğunluq sindromlarının erqoterapiya idarəetməsində geniş istifadə olunan üsuldur.", purpose:"'Hamısı və ya heç nə' fəaliyyət nümunəsinin (yaxşı gündə hər şeyi etmək, sonra tükənmək) qarşısını almaq.", usage:"Fəaliyyətlər kiçik, sabit dozalara bölünür və enerji səviyyəsinə uyğun tarazlı şəkildə paylaşdırılır.", outcomes:"Simptomların kəskin dalğalanmasını azaldır, sabit funksionallıq təmin edir."},
  en:{title:"Pacing (Energy Management)", about:"A method widely used in occupational therapy management of chronic illness and fatigue syndromes.", purpose:"To prevent the 'all-or-nothing' activity pattern (doing everything on a good day, then crashing).", usage:"Activities are broken into small, consistent doses and distributed evenly according to energy level.", outcomes:"Reduces sharp symptom flare-ups and supports stable functioning."},
  ru:{title:"Пейсинг (управление энергией)", about:"Метод, широко используемый в эрготерапевтическом ведении хронических заболеваний и синдромов усталости.", purpose:"Предотвратить модель поведения «всё или ничего» (делать всё в хороший день, а потом выгорать).", usage:"Активность разбивается на небольшие, постоянные дозы и равномерно распределяется в соответствии с уровнем энергии.", outcomes:"Снижает резкие обострения симптомов, обеспечивает стабильное функционирование."},
  tr:{title:"Pacing (Enerji Yönetimi)", about:"Kronik hastalık ve yorgunluk sendromlarının ergoterapi yönetiminde yaygın kullanılan bir yöntemdir.", purpose:"'Ya hep ya hiç' etkinlik örüntüsünü (iyi günde her şeyi yapıp sonra tükenmeyi) önlemek.", usage:"Etkinlikler küçük, sabit dozlara bölünür ve enerji düzeyine uygun, dengeli şekilde dağıtılır.", outcomes:"Semptomların keskin dalgalanmasını azaltır, sabit işlevselliği sağlar."}
},
"interoseptiv-meruzeetme": {
  az:{title:"İnteroseptiv Məruzəetmə", about:"Panik Pozuntusunun müalicəsində istifadə olunan spesifik məruzəetmə formasıdır (Barlow və b.).", purpose:"Bədən simptomlarının (ürək döyüntüsü, baş gicəllənmə) özlərinin təhlükəli olmadığını, birbaşa təcrübədən keçməklə göstərmək.", usage:"Nəzarətli şəkildə (yerində qaçma, fırlanma, nazik boru ilə nəfəs) panikə bənzər fiziki simptomlar yaradılır və təhlükəsiz olduğu müşahidə edilir.", outcomes:"Bədən simptomlarından qorxunu azaldaraq panik atakların tezliyini aşağı salır."},
  en:{title:"Interoceptive Exposure", about:"A specific form of exposure used in treating Panic Disorder (Barlow et al.).", purpose:"To show, through direct experience, that bodily symptoms (racing heart, dizziness) are not dangerous in themselves.", usage:"Panic-like physical symptoms are deliberately created in a controlled way (running in place, spinning, breathing through a thin straw), and their safety is observed firsthand.", outcomes:"Reduces fear of bodily symptoms and lowers the frequency of panic attacks."},
  ru:{title:"Интероцептивная экспозиция", about:"Специфическая форма экспозиции, используемая при лечении панического расстройства (Барлоу и др.).", purpose:"Показать на собственном опыте, что телесные симптомы (учащённое сердцебиение, головокружение) сами по себе не опасны.", usage:"Контролируемым образом (бег на месте, кружение, дыхание через тонкую трубочку) намеренно вызываются похожие на панику физические симптомы, и на собственном опыте наблюдается их безопасность.", outcomes:"Снижает страх перед телесными симптомами, уменьшает частоту панических атак."},
  tr:{title:"İnteroseptif Maruz Bırakma", about:"Panik Bozukluğu tedavisinde kullanılan özel bir maruz bırakma biçimidir (Barlow ve ark.).", purpose:"Beden semptomlarının (kalp çarpıntısı, baş dönmesi) kendi başına tehlikeli olmadığını doğrudan deneyimle göstermek.", usage:"Kontrollü bir şekilde (yerinde koşma, dönme, ince bir borudan nefes alma) panik benzeri fiziksel semptomlar oluşturulur ve güvenli olduğu birebir gözlemlenir.", outcomes:"Beden semptomlarından korkuyu azaltarak panik atak sıklığını düşürür."}
},
"y-bocs": {
  az:{title:"Y-BOCS (Yale-Brown Obsessive Compulsive Scale)", about:"1989-cu ildə Goodman və həmkarları tərəfindən hazırlanmış, OKB üzrə qızıl standart klinik qiymətləndirmə vasitəsidir.", purpose:"Obsessiya və kompulsiyaların şiddətini, tezliyini və funksionallığa təsirini standartlaşdırılmış şəkildə ölçmək.", usage:"Struktur müsahibə formatında, obsessiya və kompulsiya üçün ayrı-ayrı 5 sualdan (vaxt, narahatlıq, müqavimət, nəzarət və s.) ibarətdir, 0-40 aralığında bal verir.", outcomes:"16-23 bal orta, 24-31 ağır, 32+ son dərəcə ağır OKB göstəricisi sayılır; müalicə effektivliyini izləməkdə istifadə olunur."},
  en:{title:"Y-BOCS (Yale-Brown Obsessive Compulsive Scale)", about:"A gold-standard clinical assessment instrument for OCD, developed by Goodman and colleagues in 1989.", purpose:"To measure the severity, frequency, and functional impact of obsessions and compulsions in a standardized way.", usage:"A structured interview format with 5 separate questions for obsessions and compulsions each (time spent, distress, resistance, control, etc.), scored from 0-40.", outcomes:"16-23 is considered moderate, 24-31 severe, 32+ extreme OCD; used to track treatment effectiveness."},
  ru:{title:"Y-BOCS (Йельско-Брауновская шкала обсессивно-компульсивных расстройств)", about:"Золотой стандарт клинической оценки ОКР, разработанный Гудманом и коллегами в 1989 году.", purpose:"Стандартизированно измерить тяжесть, частоту и функциональное влияние обсессий и компульсий.", usage:"Формат структурированного интервью с 5 отдельными вопросами для обсессий и компульсий (затраченное время, дистресс, сопротивление, контроль и др.), оценка от 0 до 40.", outcomes:"16-23 балла — среднее, 24-31 — тяжёлое, 32+ — крайне тяжёлое ОКР; используется для отслеживания эффективности лечения."},
  tr:{title:"Y-BOCS (Yale-Brown Obsesif Kompulsif Ölçeği)", about:"1989'da Goodman ve meslektaşları tarafından geliştirilen, OKB için altın standart klinik değerlendirme aracıdır.", purpose:"Obsesyon ve kompulsiyonların şiddetini, sıklığını ve işlevselliğe etkisini standartlaştırılmış şekilde ölçmek.", usage:"Yapılandırılmış görüşme formatında, obsesyon ve kompulsiyon için ayrı ayrı 5 sorudan (zaman, sıkıntı, direnç, kontrol vb.) oluşur, 0-40 aralığında puan verir.", outcomes:"16-23 puan orta, 24-31 ağır, 32+ son derece ağır OKB göstergesi sayılır; tedavi etkinliğini izlemede kullanılır."}
},
"phq-9": {
  az:{title:"PHQ-9 (Patient Health Questionnaire-9)", about:"Depressiyanın skrininqi üçün ən geniş istifadə olunan özünüqiymətləndirmə alətlərindən biridir (Kroenke və Spitzer, 2001).", purpose:"Son 2 həftədəki depressiv simptomların şiddətini sürətli və etibarlı şəkildə ölçmək.", usage:"9 sual, hər biri 0-3 arası bal ilə qiymətləndirilir (heç vaxt-demək olar hər gün), ümumi bal 0-27 aralığındadır.", outcomes:"5-9 yüngül, 10-14 orta, 15-19 orta-ağır, 20-27 ağır depressiya səviyyəsini göstərir."},
  en:{title:"PHQ-9 (Patient Health Questionnaire-9)", about:"One of the most widely used self-report screening tools for depression (Kroenke & Spitzer, 2001).", purpose:"To quickly and reliably measure the severity of depressive symptoms over the past 2 weeks.", usage:"9 questions, each scored 0-3 (not at all-nearly every day), with a total score ranging from 0-27.", outcomes:"5-9 indicates mild, 10-14 moderate, 15-19 moderately severe, and 20-27 severe depression."},
  ru:{title:"PHQ-9 (Опросник здоровья пациента-9)", about:"Один из наиболее широко используемых инструментов самооценки для скрининга депрессии (Кроенке и Спитцер, 2001).", purpose:"Быстро и надёжно измерить тяжесть депрессивных симптомов за последние 2 недели.", usage:"9 вопросов, каждый оценивается от 0 до 3 (совсем нет — почти каждый день), общий балл от 0 до 27.", outcomes:"5-9 баллов — лёгкая, 10-14 — умеренная, 15-19 — умеренно тяжёлая, 20-27 — тяжёлая депрессия."},
  tr:{title:"PHQ-9 (Hasta Sağlığı Anketi-9)", about:"Depresyon taraması için en yaygın kullanılan öz-bildirim araçlarından biridir (Kroenke ve Spitzer, 2001).", purpose:"Son 2 haftadaki depresif semptomların şiddetini hızlı ve güvenilir şekilde ölçmek.", usage:"9 soru, her biri 0-3 arası puanlanır (hiç değil-neredeyse her gün), toplam puan 0-27 aralığındadır.", outcomes:"5-9 hafif, 10-14 orta, 15-19 orta-ağır, 20-27 ağır depresyon düzeyini gösterir."}
},
"conners": {
  az:{title:"Conners Qiymətləndirmə Şkalası", about:"DEHB simptomlarının qiymətləndirilməsi üçün geniş istifadə olunan, valideyn/müəllim/özünüqiymətləndirmə formaları olan alətdir (C. Keith Conners).", purpose:"Diqqətsizlik, hiperaktivlik və impulsivlik simptomlarının şiddətini müxtəlif mühitlərdə (ev, məktəb) ölçmək.", usage:"Valideyn və müəllim ayrı-ayrılıqda anketi doldurur, nəticələr normativ nümunə ilə müqayisə edilir.", outcomes:"Diaqnostik prosesə dəstək verir və müalicə boyu simptomların izlənməsinə imkan yaradır."},
  en:{title:"Conners Rating Scale", about:"A widely used instrument for assessing ADHD symptoms, with parent/teacher/self-report forms (C. Keith Conners).", purpose:"To measure the severity of inattention, hyperactivity, and impulsivity symptoms across different settings (home, school).", usage:"The parent and teacher each fill out the questionnaire separately, and the results are compared against a normative sample.", outcomes:"Supports the diagnostic process and allows symptoms to be tracked throughout treatment."},
  ru:{title:"Шкала оценки Коннерса", about:"Широко используемый инструмент оценки симптомов СДВГ с формами для родителей/учителей/самооценки (К. Кит Коннерс).", purpose:"Измерить тяжесть симптомов невнимательности, гиперактивности и импульсивности в разных условиях (дом, школа).", usage:"Родитель и учитель заполняют опросник отдельно, результаты сравниваются с нормативной выборкой.", outcomes:"Поддерживает диагностический процесс и позволяет отслеживать симптомы на протяжении лечения."},
  tr:{title:"Conners Değerlendirme Ölçeği", about:"DEHB semptomlarının değerlendirilmesi için yaygın kullanılan, ebeveyn/öğretmen/öz-bildirim formları olan bir araçtır (C. Keith Conners).", purpose:"Dikkatsizlik, hiperaktivite ve dürtüsellik semptomlarının şiddetini farklı ortamlarda (ev, okul) ölçmek.", usage:"Ebeveyn ve öğretmen anketi ayrı ayrı doldurur, sonuçlar normatif örneklemle karşılaştırılır.", outcomes:"Tanı sürecini destekler ve tedavi boyunca semptomların izlenmesine imkân tanır."}
},
"yerkes-dodson": {
  az:{title:"Yerkes-Dodson Əyrisi", about:"1908-ci ildə Robert Yerkes və John Dodson tərəfindən təqdim olunmuş, oyanıqlıq və performans arasındakı əlaqəni izah edən psixofizioloji modeldir.", purpose:"Həyəcanın 'düşmən' deyil, optimal səviyyədə faydalı olan bir enerji olduğunu göstərmək.", usage:"Performans-oyanıqlıq əlaqəsi tərs-U formasında təsvir olunur: çox aşağı və çox yüksək oyanıqlıq performansı aşağı salır, orta səviyyə isə optimaldır.", outcomes:"Klientə həyəcanı 'yox etmək' deyil, 'tənzimləmək' məqsədini anlamağa kömək edir."},
  en:{title:"Yerkes-Dodson Curve", about:"A psychophysiological model presented by Robert Yerkes and John Dodson in 1908, explaining the relationship between arousal and performance.", purpose:"To show that excitement isn't the 'enemy' — at an optimal level it's actually a useful source of energy.", usage:"The performance-arousal relationship is depicted as an inverted-U: both very low and very high arousal lower performance, while a moderate level is optimal.", outcomes:"Helps the client understand the goal isn't to 'eliminate' excitement, but to 'regulate' it."},
  ru:{title:"Кривая Йеркса-Додсона", about:"Психофизиологическая модель, представленная Робертом Йерксом и Джоном Додсоном в 1908 году, объясняющая связь между возбуждением и результативностью.", purpose:"Показать, что волнение — не «враг»: на оптимальном уровне это полезный источник энергии.", usage:"Связь результативности и возбуждения изображается в виде перевёрнутой U: и слишком низкое, и слишком высокое возбуждение снижают результативность, тогда как средний уровень оптимален.", outcomes:"Помогает клиенту понять, что цель не «убрать» волнение, а «регулировать» его."},
  tr:{title:"Yerkes-Dodson Eğrisi", about:"1908'de Robert Yerkes ve John Dodson tarafından ortaya konan, uyarılma ve performans arasındaki ilişkiyi açıklayan psikofizyolojik bir modeldir.", purpose:"Heyecanın 'düşman' değil, optimal düzeyde faydalı bir enerji olduğunu göstermek.", usage:"Performans-uyarılma ilişkisi ters-U şeklinde tasvir edilir: hem çok düşük hem çok yüksek uyarılma performansı düşürür, orta düzey ise optimaldir.", outcomes:"Danışana heyecanı 'yok etmek' değil, 'düzenlemek' amacını anlamada yardımcı olur."}
},
"abc-modeli": {
  az:{title:"ABC Davranış Modeli", about:"Tətbiqi Davranış Analizinin (ABA) əsas çərçivəsidir — Antecedent (Tetikləyici) → Behavior (Davranış) → Consequence (Nəticə).", purpose:"Problemli davranışın hansı kontekstdə baş verdiyini və hansı funksiyaya (diqqət, qaçış, stimul) xidmət etdiyini müəyyənləşdirmək.", usage:"Davranışdan əvvəlki tetikləyici, davranışın özü və ondan sonra baş verən nəticə sistemli şəkildə qeydə alınır.", outcomes:"Müdaxilə planının fərdiləşdirilməsi üçün əsas məlumat bazası yaradır."},
  en:{title:"ABC Behavior Model", about:"The core framework of Applied Behavior Analysis (ABA) — Antecedent → Behavior → Consequence.", purpose:"To identify the context in which a problem behavior occurs and the function it serves (attention, escape, stimulation).", usage:"The trigger preceding the behavior, the behavior itself, and the consequence that follows are systematically recorded.", outcomes:"Creates the core data basis for individualizing an intervention plan."},
  ru:{title:"Модель поведения ABC", about:"Основная схема прикладного анализа поведения (ABA) — Antecedent (предшествующее) → Behavior (поведение) → Consequence (последствие).", purpose:"Определить, в каком контексте возникает проблемное поведение и какую функцию оно выполняет (внимание, избегание, стимуляция).", usage:"Систематически фиксируются триггер, предшествующий поведению, само поведение и последующее последствие.", outcomes:"Создаёт основную базу данных для индивидуализации плана вмешательства."},
  tr:{title:"ABC Davranış Modeli", about:"Uygulamalı Davranış Analizinin (ABA) temel çerçevesidir — Antecedent (Tetikleyici) → Behavior (Davranış) → Consequence (Sonuç).", purpose:"Sorunlu davranışın hangi bağlamda ortaya çıktığını ve hangi işleve (dikkat, kaçış, uyaran) hizmet ettiğini belirlemek.", usage:"Davranıştan önceki tetikleyici, davranışın kendisi ve ardından gelen sonuç sistematik olarak kaydedilir.", outcomes:"Müdahale planının bireyselleştirilmesi için temel veri tabanı oluşturur."}
},
"men-dili": {
  az:{title:"'Mən' Dili (I-Statements)", about:"Thomas Gordon-un ünsiyyət modelindən (1970-ci illər) qaynaqlanan, ittihamedici dili azaldan kommunikasiya texnikasıdır.", purpose:"Digər tərəfi müdafiəyə keçirməyən, öz hiss və ehtiyacını aydın ifadə edən danışıq tərzi öyrətmək.", usage:"'Sən heç vaxt...' əvəzinə 'Mən ... hiss edirəm, çünki ..., mənə lazımdır ki, ...' strukturundan istifadə olunur.", outcomes:"Münaqişələrin kəskinliyini azaldır, qarşılıqlı anlaşmanı asanlaşdırır."},
  en:{title:"'I' Language (I-Statements)", about:"A communication technique reducing accusatory language, rooted in Thomas Gordon's communication model (1970s).", purpose:"To teach a way of speaking that clearly expresses one's own feeling and need, without putting the other person on the defensive.", usage:"Instead of 'you never...', the structure 'I feel... because..., what I need is...' is used.", outcomes:"Reduces the intensity of conflicts, makes mutual understanding easier."},
  ru:{title:"Язык «Я» (Я-высказывания)", about:"Коммуникативная техника, снижающая обвинительный тон речи, восходящая к модели общения Томаса Гордона (1970-е годы).", purpose:"Научить способу говорить, ясно выражающему собственное чувство и потребность, не ставя собеседника в defensive позицию.", usage:"Вместо «ты никогда...» используется структура «Я чувствую..., потому что..., мне нужно, чтобы...».", outcomes:"Снижает накал конфликтов, облегчает взаимопонимание."},
  tr:{title:"'Ben' Dili (I-Statements)", about:"Thomas Gordon'un iletişim modelinden (1970'ler) kaynaklanan, suçlayıcı dili azaltan bir iletişim tekniğidir.", purpose:"Karşı tarafı savunmaya geçirmeyen, kendi duygu ve ihtiyacını açıkça ifade eden bir konuşma biçimi öğretmek.", usage:"'Sen hiç...' yerine 'Ben ... hissediyorum, çünkü ..., ihtiyacım olan ...' yapısı kullanılır.", outcomes:"Çatışmaların şiddetini azaltır, karşılıklı anlayışı kolaylaştırır."}
},
"koqnitiv-ucbucaq": {
  az:{title:"Koqnitiv Üçbucaq (Düşüncə-Hiss-Davranış)", about:"Aaron Beck-in Koqnitiv modelinin əsas vizual alətidir.", purpose:"Düşüncələrin hiss və davranışlara necə birbaşa təsir etdiyini sadə, əyani şəkildə göstərmək.", usage:"Konkret bir vəziyyət üzərində düşüncə, bundan yaranan hiss və nəticədəki davranış ayrı-ayrı yazılıb əlaqələndirilir.", outcomes:"Klientin öz koqnitiv nümunələrini tanıma bacarığını artırır."},
  en:{title:"Cognitive Triangle (Thought-Feeling-Behavior)", about:"The core visual tool of Aaron Beck's Cognitive model.", purpose:"To show, simply and visually, how thoughts directly affect feelings and behavior.", usage:"For a specific situation, the thought, the resulting feeling, and the resulting behavior are each written down separately and connected.", outcomes:"Increases the client's ability to recognize their own cognitive patterns."},
  ru:{title:"Когнитивный треугольник (Мысль-Чувство-Поведение)", about:"Основной визуальный инструмент когнитивной модели Аарона Бека.", purpose:"Просто и наглядно показать, как мысли напрямую влияют на чувства и поведение.", usage:"Для конкретной ситуации отдельно записываются мысль, возникшее из неё чувство и итоговое поведение, после чего они связываются между собой.", outcomes:"Повышает способность клиента распознавать собственные когнитивные паттерны."},
  tr:{title:"Bilişsel Üçgen (Düşünce-Duygu-Davranış)", about:"Aaron Beck'in Bilişsel modelinin temel görsel aracıdır.", purpose:"Düşüncelerin duygu ve davranışları nasıl doğrudan etkilediğini basit, görsel bir şekilde göstermek.", usage:"Somut bir durum üzerinden düşünce, bundan doğan duygu ve sonuçtaki davranış ayrı ayrı yazılıp ilişkilendirilir.", outcomes:"Danışanın kendi bilişsel kalıplarını tanıma becerisini artırır."}
},
"qorxu-termometri": {
  az:{title:"Qorxu/Narahatlıq Termometri (SUDS)", about:"Subjective Units of Distress Scale — Wolpe tərəfindən təqdim olunmuş 0-10 (və ya 0-100) subyektiv narahatlıq ölçü vasitəsidir.", purpose:"Narahatlığın intensivliyini sadə, izlənə bilən rəqəmə çevirmək.", usage:"Klientdən verilən anda narahatlığını 0 (tam sakit) - 10 (ən yüksək) arası qiymətləndirməsi istənilir; məruzəetmə boyu davamlı izlənilir.", outcomes:"İrəliləyişin obyektiv izlənməsinə və məruzəetmə sürətinin tənzimlənməsinə imkan verir."},
  en:{title:"Fear/Anxiety Thermometer (SUDS)", about:"Subjective Units of Distress Scale — a 0-10 (or 0-100) subjective anxiety measure introduced by Wolpe.", purpose:"To turn the intensity of anxiety into a simple, trackable number.", usage:"The client is asked to rate their current anxiety from 0 (fully calm) to 10 (highest); tracked continuously throughout exposure.", outcomes:"Allows objective tracking of progress and adjustment of the pace of exposure."},
  ru:{title:"Термометр страха/тревоги (SUDS)", about:"Subjective Units of Distress Scale — субъективная шкала тревоги от 0 до 10 (или 0-100), предложенная Вольпе.", purpose:"Превратить интенсивность тревоги в простое, отслеживаемое число.", usage:"Клиента просят оценить текущую тревогу от 0 (полностью спокоен) до 10 (максимум); отслеживается непрерывно на протяжении экспозиции.", outcomes:"Позволяет объективно отслеживать прогресс и регулировать темп экспозиции."},
  tr:{title:"Korku/Kaygı Termometresi (SUDS)", about:"Subjective Units of Distress Scale — Wolpe tarafından ortaya konan, 0-10 (ya da 0-100) öznel kaygı ölçüm aracıdır.", purpose:"Kaygının yoğunluğunu basit, izlenebilir bir sayıya dönüştürmek.", usage:"Danışandan mevcut kaygısını 0 (tamamen sakin) ile 10 (en yüksek) arasında değerlendirmesi istenir; maruz bırakma boyunca sürekli izlenir.", outcomes:"İlerlemenin nesnel olarak izlenmesine ve maruz bırakma hızının ayarlanmasına imkân tanır."}
},
"ezele-bosaltma": {
  az:{title:"Mütərəqqi Əzələ Boşaltma (PMR)", about:"Edmund Jacobson tərəfindən 1920-ci illərdə hazırlanmış relaksasiya texnikasıdır.", purpose:"Bədəndəki fiziki gərginliyi sistemli şəkildə azaltmaq.", usage:"Əzələ qrupları ardıcıl olaraq (ayaqdan başa doğru) əvvəlcə sıxılır, sonra birdən buraxılır, fərq hiss edilir.", outcomes:"Fiziki gərginliyi və subyektiv narahatlığı azaldır, yuxu keyfiyyətini yaxşılaşdırır."},
  en:{title:"Progressive Muscle Relaxation (PMR)", about:"A relaxation technique developed by Edmund Jacobson in the 1920s.", purpose:"To systematically reduce physical tension in the body.", usage:"Muscle groups are tensed in sequence (from feet to head), then suddenly released, and the difference is noticed.", outcomes:"Reduces physical tension and subjective anxiety, and improves sleep quality."},
  ru:{title:"Прогрессивная мышечная релаксация (ПМР)", about:"Техника релаксации, разработанная Эдмундом Джекобсоном в 1920-х годах.", purpose:"Систематически снижать физическое напряжение в теле.", usage:"Группы мышц последовательно (от ступней к голове) сначала напрягаются, затем резко расслабляются, замечается разница.", outcomes:"Снижает физическое напряжение и субъективную тревогу, улучшает качество сна."},
  tr:{title:"Kademeli Kas Gevşetme (PMR)", about:"Edmund Jacobson tarafından 1920'lerde geliştirilen bir gevşeme tekniğidir.", purpose:"Bedendeki fiziksel gerginliği sistematik olarak azaltmak.", usage:"Kas grupları sırayla (ayaktan başa doğru) önce gerilir, sonra aniden bırakılır, fark hissedilir.", outcomes:"Fiziksel gerginliği ve öznel kaygıyı azaltır, uyku kalitesini iyileştirir."}
},
"xatire-qutusu": {
  az:{title:"Xatirə Qutusu (Memory Box / Continuing Bonds)", about:"Yas terapiyasında 'continuing bonds' (davam edən bağlar) nəzəriyyəsinə əsaslanan simvolik alətdir (Klass, Silverman & Nickman, 1996).", purpose:"İtirilən şəxslə əlaqəni 'kəsmək' əvəzinə, yeni, daşına bilən formada davam etdirmək.", usage:"Şəkillər, əşyalar, yazılı xatirələr toplanaraq simvolik bir qutuda/kitabda saxlanılır.", outcomes:"Yas prosesini asanlaşdırır, itkiyə dair müsbət bağlılığı qoruyur."},
  en:{title:"Memory Box (Continuing Bonds)", about:"A symbolic tool in grief therapy based on the 'continuing bonds' theory (Klass, Silverman & Nickman, 1996).", purpose:"To carry the connection with the person who was lost forward in a new, portable form, rather than 'cutting it off.'", usage:"Photos, objects, and written memories are gathered and kept in a symbolic box or book.", outcomes:"Eases the grieving process and preserves a positive bond to the loss."},
  ru:{title:"Шкатулка памяти (Memory Box / Continuing Bonds)", about:"Символический инструмент терапии горя, основанный на теории «продолжающихся связей» (Класс, Сильверман и Никман, 1996).", purpose:"Не «обрывать» связь с ушедшим человеком, а продолжить её в новой, переносимой форме.", usage:"Фотографии, предметы, письменные воспоминания собираются и хранятся в символической шкатулке или книге.", outcomes:"Облегчает процесс горевания, сохраняет позитивную связь с утратой."},
  tr:{title:"Anı Kutusu (Memory Box / Continuing Bonds)", about:"Yas terapisinde 'süregelen bağlar' (continuing bonds) kuramına dayanan sembolik bir araçtır (Klass, Silverman & Nickman, 1996).", purpose:"Kaybedilen kişiyle bağı 'koparmak' yerine, yeni, taşınabilir bir biçimde sürdürmek.", usage:"Fotoğraflar, eşyalar, yazılı anılar toplanarak sembolik bir kutuda/kitapta saklanır.", outcomes:"Yas sürecini kolaylaştırır, kayba dair olumlu bağı korur."}
},
"5-4-3-2-1": {
  az:{title:"5-4-3-2-1 Torpaqlanma Texnikası", about:"Sensor əsaslı torpaqlanma (grounding) texnikalarından biridir, akut narahatlıq/panik anlarında istifadə olunur.", purpose:"Diqqəti həddindən artıq düşüncədən bədən və ətraf mühitin konkret hisslərinə yönəltmək.", usage:"5 görülən, 4 toxunulan, 3 eşidilən, 2 qoxulanan, 1 dadılan şey ardıcıl adlandırılır.", outcomes:"Akut narahatlıq/dissosiasiya anlarında sürətli sakitləşmə təmin edir."},
  en:{title:"5-4-3-2-1 Grounding Technique", about:"One of the sensory-based grounding techniques, used during moments of acute anxiety/panic.", purpose:"To redirect attention away from excessive thought toward concrete sensations in the body and surroundings.", usage:"5 things seen, 4 things touched, 3 things heard, 2 things smelled, 1 thing tasted are named in sequence.", outcomes:"Provides rapid calming during moments of acute anxiety/dissociation."},
  ru:{title:"Техника заземления 5-4-3-2-1", about:"Одна из сенсорных техник заземления (grounding), используемая в моменты острой тревоги/паники.", purpose:"Перенаправить внимание с избыточных мыслей на конкретные ощущения тела и окружающей обстановки.", usage:"По порядку называются 5 увиденных, 4 осязаемых, 3 услышанных, 2 обоняемых, 1 вкусовое ощущение.", outcomes:"Обеспечивает быстрое успокоение в моменты острой тревоги/диссоциации."},
  tr:{title:"5-4-3-2-1 Topraklanma Tekniği", about:"Duyusal temelli topraklanma (grounding) tekniklerinden biridir, akut kaygı/panik anlarında kullanılır.", purpose:"Dikkati aşırı düşünceden bedenin ve çevrenin somut hislerine yönlendirmek.", usage:"5 görülen, 4 dokunulan, 3 duyulan, 2 koklanan, 1 tadılan şey sırayla söylenir.", outcomes:"Akut kaygı/dissosiasyon anlarında hızlı sakinleşme sağlar."}
}
};

function findProgramKey(key){ return PROGRAMS_DB[key]; }

function renderProgram(key){
  const t = UI[currentLang()];
  const entry = PROGRAMS_DB[key];
  if(!entry) return `<p>${t.notFound}</p>`;
  const p = entry[currentLang()] || entry.az;
  let html = `<span class="m-tag">${t.programTag}</span><h3 class="m-title">${p.title}</h3>`;
  html += `<div class="m-block"><h5>${t.history}</h5><div class="m-goal">${p.about}</div></div>`;
  html += `<div class="m-block"><h5>${t.purpose}</h5><div class="m-goal">${p.purpose}</div></div>`;
  html += `<div class="m-block"><h5>${t.usage}</h5><div class="m-goal">${p.usage}</div></div>`;
  html += `<div class="m-block"><h5>${t.outcomes}</h5><div class="m-goal">${p.outcomes}</div></div>`;
  return html;
}

function openProgram(key){
  const content = renderProgram(key);
  const el = document.getElementById('programModalContent');
  const ov = document.getElementById('programModalOverlay');
  if(!el || !ov){
    // fallback: reuse session modal container if page has no dedicated program modal
    const alt = document.getElementById('modalContent');
    const altOv = document.getElementById('modalOverlay');
    if(alt && altOv){ alt.innerHTML = content; altOv.classList.add('active'); document.body.classList.add('modal-open'); }
    return;
  }
  el.innerHTML = content;
  ov.classList.add('active');
  document.body.classList.add('modal-open');
}
function closeProgram(){
  const ov = document.getElementById('programModalOverlay');
  if(ov) ov.classList.remove('active');
  if(!document.getElementById('modalOverlay') || !document.getElementById('modalOverlay').classList.contains('active')){
    document.body.classList.remove('modal-open');
  }
}
document.addEventListener('keydown', e=>{ if(e.key==='Escape') closeProgram(); });
